### PR TITLE
Get account

### PR DESCRIPTION
**Pull request by dharmdip**
Add get_account method.

### CODE REVIEW

**Comment by devn** [comment]
Hi @dharmdip,

Thanks for your contribution. Could you please submit your PR with a filled in test?

**Comment by dharmdip** [comment]
Hi @devn, 

Yes sure, i will do.

**Comment by ceaess** [comment]
@dharmdip, are you able to add a test for this? Would love to see this merged. :)

**Comment by bcobb** [comment]
Tested this out by hand, and it looks good. Thanks, @dharmdip! Sorry for such a long delay.

**Pull request merged**
